In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('(Titanic)train.csv')
df.sample(5)

PassengerId  Survived  Pclass  \
336          337         0       1   
130          131         0       3   
873          874         0       3   
186          187         1       3   
6              7         0       1   

                                                Name     Sex   Age  SibSp  \
336                        Pears, Mr. Thomas Clinton    male  29.0      1   
130                             Drazenoic, Mr. Jozef    male  33.0      0   
873                      Vander Cruyssen, Mr. Victor    male  47.0      0   
186  O'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)  female   NaN      1   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

     Parch  Ticket     Fare Cabin Embarked  
336      0  113776  66.6000    C2        S  
130      0  349241   7.8958   NaN        C  
873      0  345765   9.0000   NaN        S  
186      0  370365  15.5000   NaN        Q  
6        0   17463  51.8625   E46        S

In [3]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [4]:
df.sample(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
102         0       1    male  21.0      0      1  77.2875        S
291         1       1  female  19.0      1      0  91.0792        C
355         0       3    male  28.0      0      0   9.5000        S
626         0       2    male  57.0      0      0  12.3500        Q
412         1       1  female  33.0      1      0  90.0000        Q

In [5]:
x_train,x_test,y_train,y_test= train_test_split(df.drop(columns=['Survived']),df['Survived'],test_size=0.2,random_state=45)

In [6]:
x_train.sample(5)

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
357       2  female  38.0      0      0   13.0000        S
326       3    male  61.0      0      0    6.2375        S
31        1  female   NaN      1      0  146.5208        C
318       1  female  31.0      0      2  164.8667        S
350       3    male  23.0      0      0    9.2250        S

In [7]:
y_train.sample(5)

415    0
829    1
851    0
97     1
111    0
Name: Survived, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


### Filling missing values

In [9]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [10]:
# applying imputation
si_age = SimpleImputer()# if the empty in brackets it means mean
si_Embarked = SimpleImputer(strategy ='most_frequent')

x_train_age = si_age.fit_transform(x_train[['Age']])
x_train_embarked =si_Embarked.fit_transform(x_train[['Embarked']])

x_test_age = si_age.transform(x_test[['Age']])
x_test_embarked =si_Embarked.transform(x_test[['Embarked']])

In [11]:
x_train_embarked

array([['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['Q'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['Q'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['C'],
       ['C'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['C'],
       ['S'],
       ['Q'],
       ['Q'],
       ['S'],
       ['C'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
       ['S'],
      

In [12]:
x_train_age

array([[38.        ],
       [28.        ],
       [ 9.        ],
       [58.        ],
       [34.        ],
       [49.        ],
       [29.        ],
       [44.        ],
       [30.        ],
       [29.93955986],
       [20.        ],
       [16.        ],
       [29.93955986],
       [21.        ],
       [38.        ],
       [19.        ],
       [29.93955986],
       [32.        ],
       [50.        ],
       [30.        ],
       [29.93955986],
       [29.93955986],
       [29.93955986],
       [34.        ],
       [17.        ],
       [38.        ],
       [34.        ],
       [29.93955986],
       [48.        ],
       [39.        ],
       [41.        ],
       [30.        ],
       [14.5       ],
       [25.        ],
       [18.        ],
       [29.93955986],
       [39.        ],
       [19.        ],
       [29.93955986],
       [45.        ],
       [52.        ],
       [34.        ],
       [18.        ],
       [29.93955986],
       [30.        ],
       [39

In [13]:
# oneHot encoding for sex & embarked
ohe_sex = OneHotEncoder(sparse=False,handle_unknown ='ignore')
ohe_embarked = OneHotEncoder(sparse=False,handle_unknown ='ignore')

x_train_sex = ohe_sex.fit_transform(x_train[['Sex']])
x_train_embarked =ohe_embarked.fit_transform(x_train_embarked)

x_test_sex = ohe_sex.transform(x_test[['Sex']])
x_test_embarked = ohe_embarked.transform(x_test_embarked)

In [14]:
x_train_embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [15]:
x_train_sex

array([[0., 1.],
       [0., 1.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [16]:
x_train.sample(5)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
853       1  female  16.0      0      1  39.4000        S
39        3  female  14.0      1      0  11.2417        C
294       3    male  24.0      0      0   7.8958        S
295       1    male   NaN      0      0  27.7208        C
725       3    male  20.0      0      0   8.6625        S

In [17]:
x_train_rem = x_train.drop(columns=['Sex','Age','Embarked'])

In [18]:
x_test_rem = x_test.drop(columns=['Sex','Age','Embarked'])

In [19]:
x_train_transformed = np.concatenate((x_train_rem,x_train_age,x_train_sex,x_train_embarked),axis=1)
x_test_transformed = np.concatenate((x_test_rem,x_test_age,x_test_sex,x_test_embarked),axis=1)

In [20]:
x_train_transformed.shape

(712, 10)

In [21]:
x_test_transformed.shape

(179, 10)

In [22]:
clf = DecisionTreeClassifier()
clf.fit(x_train_transformed,y_train)

DecisionTreeClassifier()

In [23]:
y_pred =clf.predict(x_test_transformed)

In [24]:
y_pred

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 1, 1], dtype=int64)

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7653631284916201

In [26]:
import pickle

In [27]:
pickle.dump(ohe_sex,open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked,open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf,open('models/clf.pkl','wb'))